# Introducción

El propósito de la desestacionalización es identificar y estimar los distintos componentes de una serie temporal para comprender mejor las tendencias subyacentes, el ciclo económico y los movimientos a corto plazo de la serie. Esta técnica proporciona una perspectiva complementaria de los cambios recientes en las series macroeconómicas, permitiendo la comparación entre trimestres sin la influencia de efectos estacionales o del calendario. En este capítulo, se presentan los principios fundamentales de la desestacionalización, seguidos de una descripción de los pasos principales en los procedimientos más comunes empleados por los organismos que producen datos. También se ofrece orientación práctica sobre cómo evaluar y validar la calidad de los datos desestacionalizados. Finalmente, se abordan algunos problemas específicos relacionados con la aplicación de la desestacionalización en el contexto de las cuentas nacionales, como la comparación entre el ajuste directo y el ajuste indirecto de los agregados de las cuentas nacionales trimestrales (CNT) y la coherencia temporal con las referencias anuales.

